### ISSUE TITLE
K1M: Recut fails working with provided seeds

### ISSUE THREAD

**Issue by k1moradi** [UCLA-VAST/recut#7]
tested command:
`time nice -n 19 recut /data/20220725_17_41_55_SW220510_02_LS_6x_1000z_stitched/Ex_488_Em_525_6x_8bit2bsh_tif_deconvolved_flip_up --seeds /data/20220725_17_41_55_SW220510_02_LS_6x_1000z_stitched/soma_recut --fg-percent 0.1 --output-type eswc --open-steps 4 --close-steps 1`

Error:
`Start merge
Grid finalize time: 102.57 s
Finished stage: convert
Finished total updating within 3564.17 sec 
recut: /build/521gxvnvw53pza2mcdkl8b5300pz0s5j-source/src/recut.hpp:3255: void Recut<image_t>::operator()() [with image_t = short unsigned int]: Assertion ((void)"Root pairs must be set before beginning reconstruction", !root_pairs.empty())' failed.
Aborted
`

**Comment by kdmarrett** [comment]
Fixed in feat/no-point-inputs branch, which will be merged with master after further testing for backward compatibility
